[api_keys]
REPLICATE_API_TOKEN = "r8_sk-proj-l0VTrEBUBPhbHNHaBtum3wwuvcOUEoXMQf_a3oZI7ObDdXbtKGHOjorYlswmxRy-7PeCw0oKQIT3BlbkFJifHQua6-0Yt6h9EA6Fx2-s7aKNXmw28FW7PZmRPhOvvAvIJ9sNs6bHC0sAli53lsj93NROz6EA"
