[api_keys]
REPLICATE_API_TOKEN = "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"
